/*
 * © Copyright Mariusz Jakubowski 2012
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); 
 * you may not use this file except in compliance with the License. 
 * You may obtain a copy of the License at:
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or 
 * implied. See the License for the specific language governing 
 * permissions and limitations under the License.
 */

package org.openntf.xsp.dojox.dojo;

import org.openntf.xsp.annotations.XspGenComponent;
import org.openntf.xsp.annotations.XspGenDojoRenderer;
import org.openntf.xsp.annotations.XspGenProperty;

import com.ibm.xsp.extlib.component.dojo.form.UIDojoFormWidgetBase;

@XspGenComponent(
		description = "Dojo inline edit box", 
		displayName = "Dojo InlineEditBox", 
		tagName = "djInlineEdit",
		smallIcon = "dojox/designer/icons/DojoInlineEditBox_16.png",
		largeIcon = "dojox/designer/icons/DojoInlineEditBox_24.png",
		componentFamily = "javax.faces.Input",
		baseComponentType = "com.ibm.xsp.extlib.dojo.form.FormWidgetBase",
		paletteCategory = "Extlib DojoX"
)
@XspGenDojoRenderer(
		baseClass = "InlineEditBoxRendererBase",
		dojoModule = "dijit.InlineEditBox",
		defaultDojoType = "dijit.InlineEditBox"
)
public abstract class InlineEditBox extends UIDojoFormWidgetBase {

	@XspGenProperty(
			description = "Changing the value automatically saves it; don't have to push save button (and save button isn't even displayed)", 
			displayName = "Auto Save",
			defaultValue = "true",
			category = "dojo-widget"
	)
	protected Boolean autoSave;

	@XspGenProperty(
			description = "Save button label", 
			displayName = "Save button label",
			category = "dojo-widget"
	)
	protected String buttonSave;

	@XspGenProperty(
			description = "Cancel button label", 
			displayName = "Cancel button label",
			category = "dojo-widget"
	)
	protected String buttonCancel;
	
	//private Boolean renderAsHtml;
	
	
	@XspGenProperty(
			description = "Class name (or reference to the Class) for Editor widget", 
			displayName = "Editor",
			category = "dojo-widget"
	)
	protected String editor;

	//private String editorWrapper;
	
	//private String editorParams;
	
	@XspGenProperty(
			description = "The text that gets displayed when there is no value (so that the user has a place to click to edit)", 
			displayName = "No Value Indicator",
			category = "dojo-widget"
	)
	protected String noValueIndicator;
	

	@XspGenProperty(
			description = "Markup tag that should be generated by the control.", 
			displayName = "Tag Name",
			category = "dojo-widget"
	)
	protected String tagName;
	
}
